server:
    port: 4567
    servlet.contextPath: /api
    
spring:
    application:
        name: raffleManagerMicroservice
furnitureManagerMicroservice:
  ribbon:
    eureka:
        enabled: false
    listOfServers: http://localhost:1234
        
