server:
    port: 4567
    servlet.contextPath: /api
    
spring:
    application:
        name: raffleManagerMicroservice
ribbon:
    eureka:
        enabled: false
        
furnitureManagerMicroservice:
    ribbon:
        listOfServers: http://localhost:1234
        
