server:
    port: 4567
    servlet.contextPath: /api
    
spring:
    application:
        name: raffleManagerMicroservice
furnitureManagerMicroservice:
  ribbon:
    listOfServers: http://localhost:1234/api
        
